config/routes.rb
Rails.application.routes.draw do
  get 'order_detail/create'
  get 'order/show'

  # get 'cart_details/create'
  # get 'cart_details/update'
  # get 'cart_details/destroy'
  get 'carts/show'
  get 'shops/new'
  get 'shops/edit'

  get 'showAll', to: 'shops#shops'
  get 'search', to: 'static_pages#search'
  get 'category', to: 'static_pages#category'
  devise_for :users
  root 'static_pages#home'

  resources :books
  resources :shops do
    resources :books
    get 'order', to: 'shops#order'
    get 'bill', to: 'shops#bill'
  end

  resource :cart, only: [:show]
  resources :cart_details, only: %i[create update destroy]
  resources :order_detail, only: %i[create update destroy]
  resources :order, only: %i[update show export_bill] do
    get 'export_bill', to: 'order#export_bill', as: 'export_bill'
  end
  # as :user do
  #   get 'signin' => 'devise/sessions#new'
  #   post 'signin' => 'devise/sessions#create'
  #   delete 'signout' => 'devise/sessions#destroy'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :shop
  has_many :order_details
  has_many :cart_details
  has_and_belongs_to_many :categories, -> { order('name DESC') }
  validates :shop_id, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :amount, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  # before_action authenticate_user!
  belongs_to :user
  has_many :books, dependent: :destroy
  has_many :order_details, dependent: :destroy
  validates :user_id, presence: true
  validates :name, presence: true
  VALID_PHONE_REGEX = /0[0-9]*/
  validates :phone, presence: true, length: { minimum: 8, maximum: 11 }, format: { with: VALID_PHONE_REGEX }
  validates :address, presence: true
  # validates :description, length: { maximum: 140 }
end

app/controllers/shops_controller.rb
require 'kaminari'
class ShopsController < ApplicationController
  before_action :authenticate_user!
  def new
    @shop = current_user.shops.build
  end

  def create
    @shop = current_user.shops.build(shop_params)
    if @shop.save
      flash[:notice] = 'Shop created!'
      redirect_to @shop
    else
      flash[:alert] = 'Failed to create!'
      render 'new'
    end
  end

  def edit
    @shop = current_user.shops.find(params[:id])
  end

  def update
    @shop = current_user.shops.find(params[:id])
    if @shop.update(shop_params)
      flash[:notice] = 'Shop has been updated!'
      redirect_to showAll_path
    else
      flash[:alert] = 'Failed to update!'
      render 'edit'
    end
  end

  def show
    @shop = current_user.shops.find(params[:id])
    @books = @shop.books.order(:title).page(params[:page]).per(20)
    @order = @shop.order_details.order(:created_at)
    @book = @shop.books.build
    @category = Category.all.order(:name)
  end

  def order
    @shop = current_user.shops.find(params[:shop_id])
    @orders = @shop.order_details.where(status: false).order(:created_at).page(params[:page]).per(20)
  end

  def bill
    @shop = current_user.shops.find(params[:shop_id])
    @bills = @shop.order_details.where(status: true).order(created_at: :desc).page(params[:page]).per(20)
  end

  def showAll; end

  def shops
    return unless current_user.shops.any?

    @shops = current_user.shops.order(:name).page(params[:page]).per(10)
  end

  def destroy
    current_user.shops.find(params[:id]).destroy
    flash[:notice] = 'Deleted successfully!'
    redirect_to showAll_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :phone, :tax_code, :description)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_shop_nav.html.erb
<div class="shop-tabs container my-4">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "Product", shop_path(@shop), class: 'nav-link'%>
    </li>
    <li class="nav-item">
        <%= link_to "Order", shop_order_path(@shop), class: 'nav-link'%>
    </li>
    <li class="nav-item">
        <%= link_to "Bill", shop_bill_path(@shop), class: 'nav-link'%>
    </li>
  </ul>
</div>

app/views/shops/bill.html.erb
<%= render 'shops/shop_nav'%>
<h2>All Bill</h2>
<div class="shop-bills container-md">
      <% if @shop.order_details.any? %>
      <table class="All-orders table table-striped table-hover">
      <thead>
          <tr class="table-dark">
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Price</th>
              <th scope="col">Shipping Address</th>
              <th scope="col">Payment Method</th>
              <th scope="col">Created at</th>
          </tr>
      </thead>
      <tbody>
          <% @bills.each.with_index(1) do |bill| %>
              <%book = Book.find(bill.Book_id)%>
              <%bill_belongs = Order.find(bill.Order_id)%>
              <tr>
                  <th scope="row"><%= bill.id %></th>
                  <td><%= book.title%></td> 
                  <td><%= book.author%></td> 
                  <td><%= bill.quantity %></td>
                  <td><%= number_to_currency bill.total_price %></td>
                  <td><%= bill_belongs.shipping_address %></td>
                  <td><%= bill_belongs.payment_method %></td>
                  <td><%= bill_belongs.updated_at.strftime("%d-%m-%Y") %></td>
              </tr>
          <% end %>
      </tbody>
      </table>

    <% if @bills.total_pages > 1 %>
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

          <% if @bills.current_page == 1 %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @bills.current_page - 1)%>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% end %>
            
          <% (1..@bills.total_pages).each do |page| %>
            <% if page == @bills.current_page %>
              <li class="page-item active"><a class="page-link" href="#"><%=page%></a></li>
            <% else %>
              <li class="page-item"><a class="page-link" href="<%= url_for(page: page) %>"><%=page%></a></li>
            <% end %>
          <% end %>
        
          <% if @bills.current_page == @bills.total_pages %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @bills.current_page + 1)%>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>
  <% end %>
  </div>

app/views/shops/edit.html.erb
<% provide(:title, "Update Shop")%>
<h2>Update <%= @shop.name%> Information</h2>

<div class="row justify-content-center">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @shop, local: true) do |f| %>
            <%= render "devise/shared/error_messages", resource: @shop %>  
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true%>

            <%= f.label :address %>
            <%= f.text_field :address%>

            <%= f.label :phone %>
            <%= f.text_field :phone %>

            <%= f.label :tax_code %>
            <%= f.number_field :tax_code %>

            <%= f.label :description %>
            <%= f.text_area :description %>

            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/shops/new.html.erb
<% provide(:title, 'My Shop') %>
<h2>Create My Shop</h2>
<!-- Modal Create Shop -->

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">

  <%= form_with(model: @shop, local: true) do |f| %>
    <%= render "devise/shared/error_messages", resource: @shop %>
    <%= f.label "Name*" %>
    <%= f.text_field :name, autofocus: true, required: true%>

    <%= f.label "Address*" %>
    <%= f.text_field :address, required: true%>

    <%= f.label "Phone*" %>
    <%= f.text_field :phone, placeholder: '0123456789', required: true %>

    <%= f.label :tax_code %>
    <%= f.number_field :tax_code %>

    <%= f.label :descrition %>
    <%= f.text_area :descrition %>

    <%= f.submit "Create", class: "btn btn-primary" %>

  <% end %>

  </div>
</div>

app/views/shops/order.html.erb
<%= render 'shops/shop_nav'%>
<h2>All Orders</h2>
<div class="shop-order-processing container-md">
      <% if @shop.order_details.any? %>
      <table class="All-orders table table-striped table-hover">
      <thead>
          <tr class="table-dark">
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total Price</th>
              <th scope="col">Shipping Address</th>
              <th scope="col">Payment Method</th>
              <th scope="col">Created at</th>
              <th scope="col">Actions</th>
          </tr>
      </thead>
      <tbody>
          <% @orders.each.with_index(1) do |order| %>
              <%book = Book.find(order.Book_id)%>
              <%order_belongs = Order.find(order.Order_id)%>
              <tr>
                  <th scope="row"><%= order.id %></th>
                  <td><%= book.title%></td> 
                  <td><%= book.author%></td> 
                  <td><%= order.quantity %></td>
                  <td><%= number_to_currency order.total_price %></td>
                  <td><%= order_belongs.shipping_address %></td>
                  <td><%= order_belongs.payment_method %></td>
                  <td><%= order_belongs.created_at.strftime("%d-%m-%Y") %></td>
                  <td><%= link_to "Done", order_detail_path(order), class: 'btn btn-primary actions', method: :patch %></td>
                  <%# <td><%= link_to "Edit", edit_shop_book_path(@shop, book) <%= link_to "Delete", shop_book_path(@shop, book), method: :delete %>
              </tr>
          <% end %>
      </tbody>
      </table>

    <% if @orders.total_pages > 1 %>
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

          <% if @orders.current_page == 1 %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @orders.current_page - 1)%>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% end %>
            
          <% (1..@orders.total_pages).each do |page| %>
            <% if page == @orders.current_page %>
              <li class="page-item active"><a class="page-link" href="#"><%=page%></a></li>
            <% else %>
              <li class="page-item"><a class="page-link" href="<%= url_for(page: page) %>"><%=page%></a></li>
            <% end %>
          <% end %>
        
          <% if @orders.current_page == @orders.total_pages %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @orders.current_page + 1)%>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>
  <% end %>
  </div>

app/views/shops/shops.html.erb
<div class="shops container-md my-2">
<h2>All My Shop</h2>
<%= link_to " Add shop", new_shop_path, class: "btn btn-primary float-end mb-2 bi bi-plus-circle"%>
<% if current_user.shops.any? %>
<div class="debug_dump table-responsive">
    <table class="All-shops table table-striped table-hover">
    <thead>
        <tr class="table-dark">
            <th scope="col">#</th>
            <th scope="col">Shop Name</th>
            <th scope="col">Address</th>
            <th scope="col">Phone</th>
            <th scope="col">Tax_code</th>
            <th scope="col">Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @shops.each.with_index(1) do |shop, index| %>
            <tr>
                <th scope="row"><%= index %></th>
                <td><%= shop.name %></td>
                <td><%= shop.address %></td>
                <td><%= shop.phone %></td>
                <td><%= shop.tax_code %></td>
                <td><%= link_to "Detail", shop_path(shop)%> <%= link_to "Edit", edit_shop_path(shop)%> <%= link_to "Delete", shop_path(shop), method: :delete %> </td>
            </tr>
        <% end %>
    </tbody>
    </table> 

  <% if @shops.total_pages > 1 %>
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">

        <% if @shops.current_page == 1 %>
          <li class="page-item disabled">  
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        <% else %>
          <li class="page-item">  
            <a class="page-link" href="<%= url_for(page: @shops.current_page - 1)%>" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        <% end %>
          
        <% (1..@shops.total_pages).each do |page| %>
          <% if page == @shops.current_page %>
            <li class="page-item active"><a class="page-link" href="#"><%=page%></a></li>
          <% else %>
            <li class="page-item"><a class="page-link" href="<%= url_for(page: page) %>"><%=page%></a></li>
          <% end %>
        <% end %>
      
        <% if @shops.current_page == @shops.total_pages %>
          <li class="page-item disabled">  
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        <% else %>
          <li class="page-item">  
            <a class="page-link" href="<%= url_for(page: @shops.current_page + 1)%>" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        <% end %>
      </ul>
    </nav>
  <% end %>

</div>   
<% end %>

</div>

app/views/shops/show.html.erb
<% provide(:title, @shop.name) %>

<%= render 'shops/shop_nav'%>
<div class="shops container-md my-2">
  <h2>All Books from <%= @shop.name%></h2>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary float-end mb-2 bi bi-plus-circle" data-bs-toggle="modal" data-bs-target="#newBook">
    Add book
  </button>

  <!-- Modal -->
  <div class="modal fade" id="newBook" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New book</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= form_with(model: @book, url: shop_books_path(@shop), local: true, as: :book) do |f| %>  
              <%= render "devise/shared/error_messages", resource: @book %>
              <%= f.label "Title*" %>
              <%= f.text_field :title, autofocus: true, required: true%>

              <%= f.label :author %>
              <%= f.text_field :author%>

              <%= f.label :publisher %>
              <%= f.text_field :publisher%>

              <%= f.label :Category %>
              <%= f.select :category_ids, options_for_select(@category.map{ |c| [c.name, c.id] }, @book.category_ids), { include_hidden: false }, {class: 'multiselect-modal', multiple: 'multiple'}%>
              
              <%= f.label "Price*" %>
              <%= f.number_field :price, required: true%>

              <%= f.label "Published Year" %>
              <%= f.date_field :year%>

              <%= f.label "Amount*" %>
              <%= f.number_field :amount, required: true%>

              <%= f.label :img_url %>
              <%= f.text_field :img_url%>

              <%= f.label :description %>
              <%= f.text_area :description%>

              <%= f.submit "Create", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div>
      <% if @shop.books.any? %>
      <table class="All-books table table-striped table-hover">
      <thead>
          <tr class="table-dark">
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Price</th>
              <th scope="col">Year</th>
              <th scope="col">Amount</th>
              <th scope="col">Actions</th>
          </tr>
      </thead>
      <tbody>
          <% @books.each.with_index(1) do |book, index| %>
              <tr>
                  <th scope="row"><%= index %></th>
                  <td><%= book.title %></td>
                  <td><%= book.price %></td>
                  <td><%= book.year %></td>
                  <td><%= book.amount %></td>
                  <td><%= link_to "Edit", edit_shop_book_path(@shop, book)%> <%= link_to "Delete", shop_book_path(@shop, book), method: :delete %> </td>
              </tr>
          <% end %>
      </tbody>
      </table>

    <% if @books.total_pages > 1 %>
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

          <% if @books.current_page == 1 %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @books.current_page - 1)%>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          <% end %>
            
          <% (1..@books.total_pages).each do |page| %>
            <% if page == @books.current_page %>
              <li class="page-item active"><a class="page-link" href="#"><%=page%></a></li>
            <% else %>
              <li class="page-item"><a class="page-link" href="<%= url_for(page: page) %>"><%=page%></a></li>
            <% end %>
          <% end %>
        
          <% if @books.current_page == @books.total_pages %>
            <li class="page-item disabled">  
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% else %>
            <li class="page-item">  
              <a class="page-link" href="<%= url_for(page: @books.current_page + 1)%>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>
  <% end %>
</div>
</div>