config/routes.rb
Rails.application.routes.draw do
  get 'order_detail/create'
  get 'order/show'

  # get 'cart_details/create'
  # get 'cart_details/update'
  # get 'cart_details/destroy'
  get 'carts/show'
  get 'shops/new'
  get 'shops/edit'

  get 'showAll', to: 'shops#shops'
  get 'search', to: 'static_pages#search'
  get 'category', to: 'static_pages#category'
  devise_for :users
  root 'static_pages#home'

  resources :books
  resources :shops do
    resources :books
    get 'order', to: 'shops#order'
    get 'bill', to: 'shops#bill'
  end

  resource :cart, only: [:show]
  resources :cart_details, only: %i[create update destroy]
  resources :order_detail, only: %i[create update destroy]
  resources :order, only: %i[update show export_bill] do
    get 'export_bill', to: 'order#export_bill', as: 'export_bill'
  end
  # as :user do
  #   get 'signin' => 'devise/sessions#new'
  #   post 'signin' => 'devise/sessions#create'
  #   delete 'signout' => 'devise/sessions#destroy'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :shop
  has_many :order_details
  has_many :cart_details
  has_and_belongs_to_many :categories, -> { order('name DESC') }
  validates :shop_id, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :amount, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_shop, only: %i[edit create update destroy index]
  before_action :authenticate_user!, only: %i[edit create destroy update]
  def new; end

  def show
    @book = Book.find(params[:id])
    @shop = Shop.find(@book.shop_id)
    @cart_detail = CartDetail.new
    @categories = []
    @book.categories.each do |category|
      @categories.push category.name
    end
  end

  def index
    @categories = Category.all.order(:name)
    @books = @current_shop.books
    @books = @books.where('title LIKE ?', "%#{params[:title]}%") if params[:title].present? && (params[:title] != '')
    @books = @books.order(:title).page(params[:page]).per(12)
  end

  def edit
    @book = @current_shop.books.find(params[:id])
    @category = Category.all.order(:name)
  end

  def create
    @book = @current_shop.books.build(book_params)
    if @book.save
      flash[:notice] = 'Book created successfully!'
      redirect_to shop_path(@current_shop)
    else
      flash[:alert] = 'Failed to create! Please make sure Title, Price, Amount field not empty!'
      redirect_to shop_path(@current_shop)
    end
  end

  def update
    @book = @current_shop.books.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book has been updated!'
      redirect_to shop_path @current_shop
    else
      flash[:alert] = 'Failed to update!'
      render 'edit'
    end
  end

  def destroy
    @current_shop.books.find(params[:id]).destroy
    flash[:notice] = 'Book has been deleted!'
    redirect_to shop_path @current_shop
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :price, :year, :amount, :descrition, :img_url,
                                 category_ids: [])
  end

  def current_shop
    @current_shop = Shop.find(params[:shop_id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
    
end

app/views/books/edit.html.erb
<% provide(:title, "Update Book")%>
<h2><%= @book.title%></h2>

<div class="row justify-content-center">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @book, url: shop_book_path, local: true) do |f| %>
            <%= render "devise/shared/error_messages", resource: @book %>
            <%= f.label :title %>
            <%= f.text_field :title, autofocus: true%>

            <%= f.label :author %>
            <%= f.text_field :author%>

            <%= f.label :publisher %>
            <%= f.text_field :publisher%>

            <%= f.label :Category %>
            <%= f.select :category_ids, options_for_select(@category.map{ |c| [c.name, c.id] }, @book.category_ids), { include_hidden: false }, {class: 'js-example-basic-multiple', multiple: 'multiple'} %>
            
            <%= f.label :price %>
            <%= f.number_field :price %>

            <%= f.label :year %>
            <%= f.date_field :year %>

            <%= f.label :amount %>
            <%= f.number_field :amount %>

            <%= f.label :img_url %>
            <%= f.text_field :img_url %>

            <%= f.label :description %>
            <%= f.text_area :descrition %>

            <%= f.submit "Update", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/books/index.html.erb
<div class="banner-shop">
    <h2>Shop <%=@current_shop.name%></h2>
</div>
<div class='shop-page container-md my-4'>
    <div class="row g-4">
        <div class="col-md-3">
            <div class="store-category">
                <h4>Store Category</h4>
                <ul>
                <% @categories.each do |category| %>
                    <li><%=category.name%></li>
                <%end%>
                </ul>
            </div>
            <div class="contact-shop">
                <h4>Contact Vendor</h4>
                <div class="mb-1">
                    <input type="text" class="form-control" id="name" placeholder="Your name">
                </div>
                <div class="mb-1">
                    <input type="text" class="form-control" id="email" placeholder="you@email.com">
                </div>
                <div class="mb-1">
                    <textarea type="text" class="form-control" id="message" rows="3" placeholder="Type your message..."></textarea>
                </div>
                <div class="d-grid mb-1">
                    <button class="btn btn-danger" fullWidth>Send message</button>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="shop-info">
                <div class='shop-summary col-5'>
                    <%= image_tag(asset_path('shop-9.jpg'))%>
                    <h4><%=@current_shop.name%></h4>
                    <div><i class="bi bi-geo-alt-fill"></i><%=@current_shop.address%></div>
                    <div><i class="bi bi-telephone"></i><%=@current_shop.phone%></div>
                    <div><i class="bi bi-star"></i>4.07 rating from 30 reviews</div>
                </div>
            </div>
            <div class="shop-product">
                <h4>Product</h4>
                <div class="search w-50">
                    <%= form_with url: shop_books_path(@current_shop), method: :get, class:"d-flex align-items-center" do |f| %>
                        <%= f.text_field :title, placeholder: "Enter Book title...", class:"form-control me-2 m-auto"%>
                        <%= f.submit "Search", class:'btn btn-danger m-auto w-50'%>
                    <% end %>
                </div>
                <div class="product">
                <div class="row row-cols-1 row-cols-md-4 g-4">
                    <% @books.each do |book| %>
                            <div class="card-group">
                                <div class="card">
                                    <%= link_to(image_tag(book.img_url, alt: book.title, class: 'card-img-top'), book_path(book))%>
                                    <div class="card-body text-center">
                                        <h6 class="card-title"><%=book.title%></h6>
                                        <p class="card-text"><small class="text-muted"><%=book.author%></small></p>
                                        <p class="card-text text-danger"><b>Price: </b><%= number_to_currency book.price%></p>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                    <div class="paginate">
                        <%= paginate @books%>
                    <div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="banner-shop">
    <h2>Shop <%=@shop.name%></h2>
</div>
<div class='container book-detail g-md-2 my-5'>
    <div class="row">
        <div class="col-md-4">
            <img src="<%=@book.img_url%>">
        </div>

        <div class="col-md-6">
            <h1 class='mb-4'><%=@book.title%></h1>
            <div class='author'>
                <b>Author: </b> <span><%=@book.author%></span>
            </div>
            <div class='price my-3'>
                <b>Price: </b><%= number_to_currency @book.price%>
            </div>
            <div class='my-3'>
               <p><%=@book.descrition%></p>
            </div>
            <div class="container-fluid my-3">
                <div class="row">
                    <div class="col-4">
                        <b>Publisher: </b>
                    </div>
                    <div class="col ms-auto"><%=@book.publisher%></div>
                </div>
                <div class="row">
                    <div class="col-4">
                       <b>Year of publishing: </b>
                    </div>
                    <div class="col ms-auto"><%=@book.year%></div>
                </div>
                <div class="row">
                    <div class="col-4">
                       <b>Available in stock: </b>
                    </div>
                    <div class="col ms-auto"><%=@book.amount%></div>
                </div>
                <div class="row">
                    <div class="col-4">
                       <b>Product ID: </b>
                    </div>
                    <div class="col ms-auto"><%=@book.id%></div>
                </div>
                <div class="row">
                    <div class="col-4">
                       <b>Category: </b>
                    </div>
                    <div class="col ms-auto">
                        <%= @categories.join(", ") %>
                    </div>
                </div>
            </div>

            <% if user_signed_in? %>
                <div class='buynow'>
                    <div class='row g-4'>
                        <%= form_with model: @cart_detail,url: cart_details_path, method: :post do |f| %>
                            <%= f.hidden_field :book_id, value: @book.id %>
                            <%= f.hidden_field :status, value: false %>
                            <%= f.number_field :quantity, value: 1, min: 1, max: @book.amount%>
                            <%= f.submit "Add to cart", class: 'btn btn-dark ms-3 bi bi-cart3 px-2'%>
                        <% end %>
                    </div>
                </div>
            <% else %>
             <i>Login to buy this product</i>
            <% end %>
        </div>
    </div>
</div>

<div class="related-book-in-shop">
    <h2>Related Products</h2>
    <div class="my-5">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            <% @shop.books.take(4).each do |book| %>
                <div class="card-group">
                    <div class="card">
                        <%= link_to(image_tag(book.img_url, alt: book.title, class: 'card-img-top'), book_path(book))%>
                        <div class="card-body text-center">
                            <h6 class="card-title"><%=book.title%></h6>
                            <p class="card-text"><small class="text-muted"><%=book.author%></small></p>
                            <p class="card-text text-danger"><b>Price: </b><%= number_to_currency book.price%></p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="d-grid gap-2 col-lg-4 mx-auto">
        <%# <button type="button" class="btn btn-dark btn-lg" >Discovery More Book In Shop</button> %>
        <%= button_to "Discovery More Book In Shop", shop_books_path(@shop.id), class:"btn btn-dark btn-lg", method: :get%>
    </div>
</div>