config/routes.rb
Rails.application.routes.draw do
  get 'order_detail/create'
  get 'order/show'

  # get 'cart_details/create'
  # get 'cart_details/update'
  # get 'cart_details/destroy'
  get 'carts/show'
  get 'shops/new'
  get 'shops/edit'

  get 'showAll', to: 'shops#shops'
  get 'search', to: 'static_pages#search'
  get 'category', to: 'static_pages#category'
  devise_for :users
  root 'static_pages#home'

  resources :books
  resources :shops do
    resources :books
    get 'order', to: 'shops#order'
    get 'bill', to: 'shops#bill'
  end

  resource :cart, only: [:show]
  resources :cart_details, only: %i[create update destroy]
  resources :order_detail, only: %i[create update destroy]
  resources :order, only: %i[update show export_bill] do
    get 'export_bill', to: 'order#export_bill', as: 'export_bill'
  end
  # as :user do
  #   get 'signin' => 'devise/sessions#new'
  #   post 'signin' => 'devise/sessions#create'
  #   delete 'signout' => 'devise/sessions#destroy'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_details

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :current_cart
  before_action :authenticate_user!
  def show
    @cart_details = current_cart.cart_details
    @sub_total = @cart_details.sum{|cart_detail| cart_detail.total_price}
    @voucher = 0
    @total = @sub_total - @voucher
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_totals.html.erb
<div class="cart-totals">
    <h3>Cart totals</h3>
    <table class="table shop-table align-middle" >
        <tbody>
            <tr class="cart-subtotal">
                <td class="table-dark col-3">Subtotal</th>
                <td colspan="2"><%= number_to_currency 0%></td>
            </tr>
            <tr class="cart-coupon">
                <td class="table-dark col-3">Discount</th>
                <td colspan="2"><%= number_to_currency 0%></td>
            </tr>
            <tr class="order-total">
                <td class="table-dark col-3">Total</th>
                <td colspan="2"><%= number_to_currency 0%></td>
            </tr>
        </tbody>
    </table>
    <div class="proceed-to-checkout my-2">
        <%= button_to "Proceed to checkout", order_show_path, class: 'btn btn-danger btn-lg w-100', disabled: true, method: :get%>
    </div>
</div>
<div style="clear: both;"></div>

app/views/carts/show.html.erb
<% provide(:title, 'Cart')%>

<div class="banner-shop">
    <h2>Cart</h2>
</div>
<div class="cart">
    <div class="container cart-table">
        <table class="table align-middle">
            <thead>
                <tr class="table-header">
                    <th scope="col"></th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Sub_total</th>
                    <th scope="col">Remove</th>
                </tr>
            </thead>
            <tbody>
                <% @cart_details.each do |item| %>
                    <tr data-id="<%=item.id%>">
                        <td class="status"><input type="checkbox" value="" ></td>
                        <td class="title"><%= link_to image_tag(item.book.img_url) + item.book.title, book_path(item.book)%></td>
                        <td class="price"><%= number_to_currency item.book.price%></td>
                        <td class="quantity">
                            <button class="increase bi bi-plus-lg mx-2"></button>
                            <input type="number" value="<%= item.quantity%>" disabled/>
                            <button class="decrease bi bi-dash-lg mx-2"></button>
                        </td>
                        <td class="sub-total"><%= number_to_currency item.total_price%></td>
                        <td class="action">
                            <%# <i class= 'btn btn-danger bi bi-x-lg'></i> %>
                            <%= link_to '', cart_detail_path(item), method: :delete, class: 'btn btn-danger bi bi-x-lg', remote: true %> 
                        </td>
                    </tr>
                <% end %>

                <tr>
                    <td colspan="2" class="cart-coupon">
                        <span class="input-group cart-coupon-inner">
                            <div class="input-group-text" id="btnGroupIcon"> <i class="bi bi-cash-coin"></i></div>
                            <input type="text" class="form-control" placeholder="Coupon Code" aria-label="Input group example" aria-describedby="btnGroupAddon">
                            <button type="button" class="btn btn-outline-secondary">Apply Coupon</button>
                        </span>
                    </td>
                    <td colspan="4" class="actions">
                        <div class="actions-inner">
                            <%= link_to "Continue Shopping", category_path, class: "btn btn-outline-dark"%>
                            <button class="btn btn-dark" disabled>Update Cart</button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <%= render "carts/cart_totals"%>
</div>