config/routes.rb
Rails.application.routes.draw do
  get 'order_detail/create'
  get 'order/show'

  # get 'cart_details/create'
  # get 'cart_details/update'
  # get 'cart_details/destroy'
  get 'carts/show'
  get 'shops/new'
  get 'shops/edit'

  get 'showAll', to: 'shops#shops'
  get 'search', to: 'static_pages#search'
  get 'category', to: 'static_pages#category'
  devise_for :users
  root 'static_pages#home'

  resources :books
  resources :shops do
    resources :books
    get 'order', to: 'shops#order'
    get 'bill', to: 'shops#bill'
  end

  resource :cart, only: [:show]
  resources :cart_details, only: %i[create update destroy]
  resources :order_detail, only: %i[create update destroy]
  resources :order, only: %i[update show export_bill] do
    get 'export_bill', to: 'order#export_bill', as: 'export_bill'
  end
  # as :user do
  #   get 'signin' => 'devise/sessions#new'
  #   post 'signin' => 'devise/sessions#create'
  #   delete 'signout' => 'devise/sessions#destroy'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # protect_from_forgery with: :exception

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   added_attrs = %i[phone email password password_confirmation address]
  #   devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  #   devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  # end
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :shop
  has_many :order_details
  has_many :cart_details
  has_and_belongs_to_many :categories, -> { order('name DESC') }
  validates :shop_id, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :amount, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_details

end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
  belongs_to :cart
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :Order
  belongs_to :Book
  belongs_to :Shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  # before_action authenticate_user!
  belongs_to :user
  has_many :books, dependent: :destroy
  has_many :order_details, dependent: :destroy
  validates :user_id, presence: true
  validates :name, presence: true
  VALID_PHONE_REGEX = /0[0-9]*/
  validates :phone, presence: true, length: { minimum: 8, maximum: 11 }, format: { with: VALID_PHONE_REGEX }
  validates :address, presence: true
  # validates :description, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :cart, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # attr_accessor :address, :name, :email

  # before_save :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  #   devise_parameter_sanitizer.permit(:account_update,
  #                                     keys: %i[name email password password_confirmation current_password])
  # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_shop, only: %i[edit create update destroy index]
  before_action :authenticate_user!, only: %i[edit create destroy update]
  def new; end

  def show
    @book = Book.find(params[:id])
    @shop = Shop.find(@book.shop_id)
    @cart_detail = CartDetail.new
    @categories = []
    @book.categories.each do |category|
      @categories.push category.name
    end
  end

  def index
    @categories = Category.all.order(:name)
    @books = @current_shop.books
    @books = @books.where('title LIKE ?', "%#{params[:title]}%") if params[:title].present? && (params[:title] != '')
    @books = @books.order(:title).page(params[:page]).per(12)
  end

  def edit
    @book = @current_shop.books.find(params[:id])
    @category = Category.all.order(:name)
  end

  def create
    @book = @current_shop.books.build(book_params)
    if @book.save
      flash[:notice] = 'Book created successfully!'
      redirect_to shop_path(@current_shop)
    else
      flash[:alert] = 'Failed to create! Please make sure Title, Price, Amount field not empty!'
      redirect_to shop_path(@current_shop)
    end
  end

  def update
    @book = @current_shop.books.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book has been updated!'
      redirect_to shop_path @current_shop
    else
      flash[:alert] = 'Failed to update!'
      render 'edit'
    end
  end

  def destroy
    @current_shop.books.find(params[:id]).destroy
    flash[:notice] = 'Book has been deleted!'
    redirect_to shop_path @current_shop
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :price, :year, :amount, :descrition, :img_url,
                                 category_ids: [])
  end

  def current_shop
    @current_shop = Shop.find(params[:shop_id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :current_cart
  before_action :authenticate_user!
  def show
    @cart_details = current_cart.cart_details
    @sub_total = @cart_details.sum{|cart_detail| cart_detail.total_price}
    @voucher = 0
    @total = @sub_total - @voucher
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_user!
  def show
    @items = current_cart.cart_details.where(status: true)
    @sub_total = @items.sum { |item| item.total_price }
    @voucher = 0
    @total = @sub_total - @voucher
    @order = Order.create!(user_id: current_user.id, status: false, total_price: @total)
    @order_details = []
    @items.each do |item|
      @order_detail = OrderDetail.create!(status: false, quantity: item.quantity, total_price: item.total_price,
                                          Book_id: item.book.id, Order_id: @order.id, Shop_id: item.book.shop_id)
      @order_details.push(@order_detail)
    end
    @order.update(order_details: @order_details)
  end

  def create; end

  def update
    order = current_user.orders.find(params[:id])
    order.update!(status: params[:status], shipping_address: params[:shipping_address],
                  payment_method: params[:payment_method])
  end

  def export_bill
    @order = current_user.orders.find(params[:order_id])
  end

  private

  def order_params
    params.require(:order).permit(:status, :total_price, :shipping_address, :payment_method, :order_details[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Book Store App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/books_helper.rb
module BooksHelper
    
end

app/helpers/cart_details_helper.rb
module CartDetailsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_detail_helper.rb
module OrderDetailHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="navbar fixed-bottom navbar-light bg-light">
    <div class="container-fluid">
    <small>The Book Store App made by Phong Nguyen</small>
    <nav>
        <ul class="d-flex flex-row">
            <li><%= link_to "About", '#'%></li>
            <li><%= link_to "Contact", "#" %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <%= image_tag(asset_path('my_logo.png'), width:"60", height:"40", class:"d-inline-block align-text-center")%>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-lg-flex justify-content-lg-between" id="navbarSupportedContent">
                <ul class="navbar-nav left mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, class: "nav-link", aria: { current: request.path == root_path ? "page" : nil }%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Category", category_path, class: "nav-link", aria: { current: request.path == category_path ? "page" : nil }%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "About", '#', class: "nav-link", aria: { current: request.path == root_path ? "page" : nil }%>
                    </li>
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to "My Shop", showAll_path, class: "nav-link", aria: { current: request.path == root_path ? "page" : nil }%>
                        </li>
                    <%end%>
                </ul>
                <div class="navbar-nav mb-2 mb-lg-0">

                    <%= form_with url: category_path, method: :get, class:"d-flex align-items-center" do |f| %>
                        <%= f.select :category, options_for_select([["All Category", 0]]+(Category.all.order(:name).map{ |c| [c.name, c.id] }), selected: 0), { include_hidden: false }, {class:"form-select me-2 m-auto"}%>
                        <%= f.text_field :title, placeholder: "Enter Title...", class:"form-control me-2 m-auto"%>
                        <%= f.submit "Search", class:'btn btn-primary m-auto w-50'%>
                    <% end %>
                   
                </div>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="dropdown-toggle" id="dropdownMenuUser" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                                    <strong> Welcome <%= current_user.name %> </strong>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start" aria-labelledby="dropdownMenuUser">
                                    <li><%= button_to "Profile", edit_user_registration_path, method: :get, class: "dropdown-item" %></li>
                                    <li><%= button_to "My Cart", carts_show_path, method: :get, class: "dropdown-item" %></li>
                                    <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                                </ul>
                            </div>
                        </li>

                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#login">Log in</a>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Sign up", new_user_registration_path, type:"button", class: 'nav-link' %>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_modal.html.erb
<!-- Modal Login -->
<div class="modal fade" id="login" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Log in</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <%= form_with(model: @user, local: true) do |f| %> 
                    <%= f.label :email %> 
                    <%= f.text_field :email %>
                    
                    <%= f.label :password %>
                    <%= f.password_field :password %>

                    <%= f.submit "Login", class: "btn btn-primary" %>
                <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="signup" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Sign up</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <%# <%= render 'devise/registrations/new', resource: User, resource_name: :user, %>
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                
                <%= f.label :password %>
                <%= f.password_field :password, autocomplete: "new-password" %>
                
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
                
                <div class="form-group">
                  <%= f.submit "Sign up", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %> 
<%= javascript_importmap_tags %>

app/views/layouts/_result.html.erb
<div class="search-result">
    <% temp = params[:title] != '' ? params[:title] : @category + " Category" %>
    <% if @results.any? %>
        <h3>Search results for '<%= temp %>'</h3>
        <div class="my-4">
            <div class="row row-cols-1 row-cols-md-4 g-4">
                <% @results.each do |book| %>
                    <div class="card-group">
                        <div class="card">
                            <%= link_to(image_tag(book.img_url, alt: book.title, class: 'card-img-top'), book_path(book))%>
                            <div class="card-body text-center">
                                <h6 class="card-title"><%=book.title%></h6>
                                <p class="card-text"><small class="text-muted"><%=book.author%></small></p>
                                <p class="card-text text-danger"><b>Price: </b><%= number_to_currency book.price%></p>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <%= paginate @results %>
       
    <% else %>
        <p class="alert alert-warning">No results found for '<%= temp %>'</p>
    <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render 'layouts/rails_default'%>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'devise/sessions/login'%>
    <div class="body">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= notice %></div> 
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-warning" role="alert"><%= alert %></div> 
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
     <%# <%= debug(params) if Rails.env.development? %> 
  </body>
   
</html>